require: rubocop-rails

Rails/Date:
  Enabled: true
  EnforcedStyle: strict
  AllowToTime: false

Rails/DefaultScope:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: true
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'lib/**/*.rake'
  AllowReads: true
  AllowWrites: false

Rails/FilePath:
  Enabled: true
  EnforcedStyle: arguments

Rails/FindBy:
  Enabled: true
  IgnoreWhereFirst: false
  Include:
    - 'app/models/**/*.rb'

Rails/OrderById:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true
  ContentTypeCompatibility: false

Rails/RequestReferer:
  Enabled: true
  EnforcedStyle: referrer

Rails/RequireDependency:
  Enabled: true

Rails/ReversibleMigrationMethodDefinition:
  Enabled: true
  Include:
    - 'db/migrate/*.rb'

Rails/SafeNavigation:
  Enabled: true
  ConvertTry: true

Rails/SaveBang:
  Enabled: true
  AllowImplicitReturn: false
  AllowedReceivers: []

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict

Rails/WhereExists:
  Enabled: true
  EnforcedStyle: where

