name: "Setup ruby and install dependencies"
description: "Setup ruby and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
